### ISSUE TITLE
api consistency

### ISSUE THREAD

**Issue by nteetor** [nteetor/yonder#10]
## preface
dull is supposed to bring more control to the programmer. This is why `...` is always an argument, the programmer can always easily add HTML attributes of their choosing. Additionally, this is why helper functions like `dropdownItem` exist. It may be cumbersome and some may ask for simple character argument values like in Shiny. However, these helper functions are part of power to the programmer deal. 

This leads into the meat of this issue. If the dull api is one that makes use of helper functions than `checkboxInput` and `radioInput` are currently inconsistent. They allow multi length character vectors to be passed as labels and values arguments. These character vectors are then converted  into individual checkbox and radio child elements. 

## proposal
I propose the following, keep `checkboxInput` and add a new helper function `checkbox`. Thus, a checkbox input is made up of checkboxes. This will allow us to build an `updateCheckbox` function and an `updateCheckboxInput`, the latter maybe not. Bootstrap allows individual checkboxes to be contextually styled, see [validation states](https://v4-alpha.getbootstrap.com/components/forms/#validation-states). In the shiny paradigm those individual checkboxes need to be a reactive input or output with an id in order to be updated by the shiny server. The helper function will make this possible by allowing the user to clearly specify an id for an individual checkbox within a checkbox input. Additionally the values of a checkbox will always appear `NULL` to the shiny server, the checkbox input still remains the proper means of  retrieving the checkbox values (its children elements). 

Thus a very simple checkbox input would look like the following,
```R
checkboxInput(
  checkbox(
    label = "Choice 1",
    value = 1
  ),
  checkbox(
    label = "Choice 2",
    value = 2
  ),
  checkbox(
    label = "Choice 3",
    value = 3
  )
)
```

## conclusion
My fear is users will not understand the distinction between `checkbox` and `checkboxInput`. They will expect a reactive value to comeback from a checkbox with an id, when in fact they need to specify and id with a checkbox input.

I am not worried about the verbosity of the api turning away users. Shiny provides very crisp ways of constructing inputs from simple character vectors. When building, coming back to, and understanding a UI I don't think this is always helpful. For those who agree there is dull.

_I have only mentioned checkboxes, but radio inputs would receive a similar treatment._

**Comment by pteetor** [comment]
This sounds like a good proposal. I'd say your fear is valid but more-or-less overblown. Just make a clear distinction in the documentation between `checkbox` and `checkboxInput`. If people don't get the distinction right away, they'll understand it after the first time they debug.

Bigger comment: Don't spin your wheels on this. Implement the scheme that makes sense to you. Then write one, two, or three sample apps. (Keep them simple.) You'll know right away if you made the correct choice. And you'll have some cool sample apps.

**Comment by nteetor** [comment]
Good advice re: testing. I'll put together the new functions tomorrow and whip together a couple example applications. 

re: distinction, I'll be sure to make the checkbox vs checkbox input distinction clear and concise. I think the examples section will help most of all.

**Comment by nteetor** [comment]
re: testing/use case, I am also not the end-all, be-all of useful scenarios for the functionality described above. However, if I cannot come up with even a simple, beneficial use case perhaps revision is in order.

**Comment by pteetor** [comment]
Good logic.

**Comment by nteetor** [comment]
Based on initial work, updating individual checkboxes feels a little cumbersome. I put together an example that uses the feature. However, the example could be reworked to use two separate checkboxInput's and then one of those inputs could be disabled. I believe more often a *set of checkboxes* would need to be disabled rather than *one checkbox of a set*. 

I still feel the api needs to include both checkboxInput and checkbox for consistency, however I will not include an `id` parameter in checkbox.

**Comment by nteetor** [comment]
* [ ] `bar` needs a rework

**Comment by nteetor** [comment]
## update

After reviewing shiny functions I became aware (perhaps reminded) how important value based arguments are to `*Input` functions. "value based" arguments help build inputs based on the user's data. Helper functions and the style of UI building initially proposed in this issue directly conflict with this data driven construction. Thus, going forward, input functions will aim to provide a consistent api for building shiny/dull apps based on data.
