### ISSUE TITLE
Installation failed, install ERROR

### ISSUE THREAD

**Issue by ghost** [nteetor/yonder#101]
Hi 

I get the below error while doing:
devtools::install_github("nteetor/yonder")

Output:
Downloading GitHub repo nteetor/yonder@master
from URL https://api.github.com/repos/nteetor/yonder/zipball/master
Installing yonder
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/Rtmpiv4i8O/devtools20274d19f1fe/nteetor-yonder-ba472c0'  \
  --library='/home/rimon/R/x86_64-pc-linux-gnu-library/3.4' --install-tests 

* installing *source* package ‘yonder’ ...
** R
Error in .install_package_code_files(".", instdir) : 
files in '/tmp/Rtmpiv4i8O/devtools20274d19f1fe/nteetor-yonder-ba472c0/R' missing from 'Collate' field:
  utilities.R
ERROR: unable to collate and parse R files for package ‘yonder’
* removing ‘/home/rimon/R/x86_64-pc-linux-gnu-library/3.4/yonder’
* restoring previous ‘/home/rimon/R/x86_64-pc-linux-gnu-library/3.4/yonder’
Installation failed: Command failed (1)

PLEASE HELP

**Comment by nteetor** [comment]
Alright, go ahead and give the installation another try.

**Comment by ghost** [comment]
Cool it worked..

Thanks mate
Cheers
