### ISSUE TITLE
Argument `multiple` in `selectInput` missing.

### ISSUE THREAD

**Issue by markusdumke** [nteetor/yonder#167]
Hi, first of all, love your work with `yonder`! I am really interested in the progress. Is `yonder` already useable for production-ready websites?

I am currently building an application with yonder and noticed that `selectInput` has no argument `multiple` despite being mentioned in the documentation.

Basically I want to recreate this `shiny::selectizeInput` behaviour in `yonder`:

```
 shiny::selectizeInput(
  "select1", label = "Filter",
  multiple = TRUE,
  selected = c("a", "b"),
  choices = c(Choose = "", letters),
  options = list(closeAfterSelect = TRUE)
)

yonder::selectInput(
  "select1", 
  multiple = TRUE,
  selected = c("a", "b"),       
  choices = c(Choose = "", letters),
  options = list(closeAfterSelect = TRUE)
)
```

> Error: invalid argument in `::()yonder()selectInput()`, `selected` must be NULL or a single value

**Comment by nteetor** [comment]
Hey @markusdumke, thanks for the questions. 

I see I removed the `multiple` argument, but forgot to drop mention of the argument from the help page description. This will be corrected in the next release.

If you are interested in replicating selectize input behaviour try out the `chipInput()`. If this input does not cover your use case please open a new issue to specifically dicuss the chip input. 

With regards to production-readiness, I tried to streamline the package API and learn as much as I could from shiny's growth and successes. I wanted to begin with a core set of utilities modeled after shiny. Yonder is new, so I am sure there are features worth adding. The next release includes new features as well as fixes. However, the core API is there already and will remain. 

In my own work I am currently building shiny applications with yonder. Unfortunately, these applications are not yet public. I'd be happy to share if and when the clients make them public.

**Comment by nteetor** [comment]
Follow up question, did you install from `nteetor/yonder@master` or CRAN?

**Comment by markusdumke** [comment]
Thanks for your reply. The `chipInput` looks nice, though I think a `selectizeInput` like in Shiny would still be nice (chips shown inside the text box). Also I miss the `closeAfterSelect` option I could pass on to `selectizeInput`.

I have been using the CRAN version.

**Comment by nteetor** [comment]
Could you describe your use case where you would prefer the chips render inside the text input? I also did a quick review of the Material Design spec for chips (https://material.io/components/chips/#). I do see a handful of situations where the chips are rendered inside the selection box. If you are interested in this feature let's move to a new issue and continue the conversation. 

I am not opposed to the close-after-selection behaviour. Feel free to open a new issue and I'll mark it as a feature request.
