### ISSUE TITLE
What exactly is Yonder?

### ISSUE THREAD

**Issue by D3SL** [nteetor/yonder#186]
Someone offhandedly mentioned this package in a conversation about using Shiny for more comprehensive web development, CRUD work, etc as opposed to read-only dashboards but as someone who isn't already a knowledgeable developer I can't figure out what exactly this is.

On a basic level what exactly _is_ Yonder and how does it differ from standard Shiny?

**Comment by nteetor** [comment]
Hey there @D3SL, thank you for the interest in yonder. I'd recommend listening to [this episode](https://shinydevseries.com/post/episode-8-yonder/) of the Shiny Dev Series. I think the interview went well and will hopefully give you an introduction to the package.

**Comment by nteetor** [comment]
Hello again @D3SL, I'm going to close this issue, but please let me know if you have any questions after watching the link I provided above. I'll be happy to revisit the issue/discussion.
