### ISSUE TITLE
Reactive values no longer work with shiny >=1.7

### ISSUE THREAD

**Issue by zross** [nteetor/yonder#193]
Hi @nteetor, the [WHO HEAT](https://github.com/WHOequity/HEATPlus-2.0) project uses Yonder extensively. With the new version of Shiny (1.7) none of the reactive values are working.

If you test out this minimal example, you'll see that with 1.7 the reactive value is not being registered. With this minimal example, 1.6 seems to work but with the HEAT project it's failing in places. With 1.5 it all works.

Any suggestions?

```r
library(shiny)

#remotes::install_version('shiny', "1.5") # works
#remotes::install_version('shiny', "1.6") # works here but not with HEAT
#remotes::install_version('shiny', "1.7") # does not work at all
ui <- fluidPage(
  yonder::selectInput('from_yonder', choices = c('a', 'b')),
  shiny::selectInput('from_shiny', label = 'a', choices = c('a', 'b'))
)

server <- function(input, output, session) {
  observeEvent(input$from_yonder, {
    print(paste('in yonder: ', input$from_yonder))
  }, ignoreInit = TRUE)
  
  observeEvent(input$from_shiny, {
    print(paste('in shiny: ', input$from_shiny))
  }, ignoreInit = TRUE)
}

shinyApp(ui, server)
```

**Comment by esegui** [comment]
the dependencies.R change is in a source file. I managed to change it but I assume I need to compile it now. I'm on Windows and it's a nightmare for me. Not really a software developer. Isn't there a version of yonder updated for newest version of shiny? Thanks

**Comment by nteetor** [comment]
I've merged Carson's fix into the main branch. However, it will take me some time to remember what state I left the main branch in. At this point I'm not sure when I will have a new version uploaded to CRAN.

**Comment by zross** [comment]
Cool Nate! We're using a forked version at the moment, but great to see this :)
