### ISSUE TITLE
shiny@async createRenderFunction() usage

### ISSUE THREAD

**Issue by nteetor** [nteetor/yonder#40]
Ask @jcheng5 about expected usage of this function when async is merged into master. I currently do not use the equivalent(?) master branch function `markRenderFunction()`.

**Comment by jcheng5** [comment]
It subsumes `markRenderFunction`. You will indeed need to use it for all of your render functions if you want them to work with async operations (promises). We can talk about it next week.

**Comment by nteetor** [comment]
I neglected to tag this issue when updating `renderTable()`, but all render functions now support async operations through `installExprFunction()` and `createRenderFunction()`.
