### ISSUE TITLE
card and cardBlock not available in package

### ISSUE THREAD

**Issue by rpodcast** [nteetor/yonder#49]
Thank you so much for creating this package!  I'm giving this a try in some basic apps to compare/contrast with the typical `shiny` widgets.  I noticed that after installing the latest version from GitHub that I cannot call the `card` and `cardBlock` functions even with the `dull:::card()` prefix.  I hope the fix is as simple as a refresh of the documentation via `devtools::document()`?  If you need additional information let me know.

**Comment by nteetor** [comment]
I am very glad to see your enthusiasm and thank you for your feedback, here and in your PRs. 

The `card` function is gone for now, but you can still search for the help page, `?card`. Look for the `textCard` function. 

The entire card-related API is subject to big changes as well as the nav-related API. Both are components with important nested elements and I have wrestled with each's API. I want to give the user the consistent flexibility dull aims to provide, while simultaneously avoiding a flood of helper functions (e.g. `cardBody`, `cardFooter`, `cardContent`, etc.) as this approach seems minimally better than bare HTML.

**Comment by nteetor** [comment]
Completely contradicting my previous comment, use the new `card()` function. 

Here is an example combining cards and tabs,

```R
shinyApp(
  ui = container(
    card(
      header = tabList(
        labels = c("Home", "Profile", "Contact"),
        panes = c("homePane", "profPane", "contactPane"),
      ),
      tabContent(
        tabPane(
          id = "homePane",
          class = "show active",
          "Vestibulum id ligula porta felis euismod semper. Cras justo
              odio, dapibus ac facilisis in, egestas eget quam."
        ),
        tabPane(
          id = "profPane",
          "Duis mollis, est non commodo luctus, nisi erat porttitor ligula,
              eget lacinia odio sem nec elit. Aenean eu leo quam. Pellentesque
              ornare sem lacinia quam venenatis vestibulum."
        ),
        tabPane(
          id = "contactPane",
          "Donec ullamcorper nulla non metus auctor fringilla. Nullam id
              dolor id nibh ultricies vehicula ut id elit."
        )
      )
    ) %>%
      margins(4) %>%
      width(50)
  ),
  server = function(input, output) {
    
  }
)
```

**Comment by nteetor** [comment]
As of commit https://github.com/nteetor/dull/commit/a4c433a3e1b60653f4803e978943e29e37fb873d the card api has stabilized. I hope you find `card()` useful. I will close this issue this weekend. If new questions come up I am happy to reopen the issue or discuss them in a new issue.
