### ISSUE TITLE
new keyword to replace "input" and "output"

### ISSUE THREAD

**Issue by nteetor** [nteetor/yonder#6]
Certain dull elements are both inputs and outputs, so it does not make sense to call functions `<element>Output()` or `<element>Input()`.

**Comment by pteetor** [comment]
Ideas:

* Can you have both `<element>Output` and `<element>Input`?
* A long time ago, someone suggested the term _transput_ to encompass both input and output. So, `<element>Transput`?

**Comment by nteetor** [comment]
Because there is one element acting as both input and output it would be very difficult to have two functions. 

I like `<element>Transput` or `<element>Throughput`. Transput is nicer because it is shorter, throughput rolls off the tongue better (for me).

**Comment by pteetor** [comment]
And "trans" is a *happening* word.


Paul

**Comment by nteetor** [comment]
using `<element>Thruput`
